fix(config): add descriptions to JSON schema properties
ubiquity-os-marketplace/command-wallet pull request #24
Opened 2024-11-26 12:54 UTC by Keyrxng

Relates to https://github.com/ubiquity-os/ubiquity-os-plugin-installer/issues/24

The logic for this config prop is outdated and should be considered for refactoring or removal I think.

2024-12-04 07:54 UTC, rndquu commented
@Keyrxng Could you resolve the code conflict?

2024-12-04 07:54 UTC, rndquu approved these changes

2024-12-04 08:27 UTC, rndquu requested changes
@Keyrxng Could you:
1. Resolve code conflicts
2. [Fix prettier](https://github.com/ubiquity-os-marketplace/command-ask/pull/41#pullrequestreview-2477647265)

2025-02-05 04:48 UTC, Keyrxng commented
Failed jest suite due to:

`
● Wallet command tests › Should handle wallet command

    Resolving address from ENS name failed: ubiquibot.eth
`

I had to bump timeouts already for the test suite but it's likely "resolved" with a re-run, but a solid fix is out-of-scope of this PR I think isn't it?

2025-02-05 07:02 UTC, rndquu approved these changes

2025-02-05 08:49 UTC, merged